# Generated by Django 2.2.2 on 2021-04-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('advert_text', models.TextField(blank=True, null=True)),
                ('price_in_dollar', models.IntegerField(default=0)),
                ('advertizer_name', models.CharField(max_length=50, null=True)),
                ('advertizer_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=15)),
                ('logo', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('total_goals', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_lose', models.IntegerField(default=0)),
                ('total_tie', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=1)),
                ('best_player', models.CharField(blank=True, max_length=15, null=True)),
                ('capital', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_club', models.CharField(max_length=15)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refre_chosen', models.CharField(max_length=15)),
                ('first_club', models.CharField(max_length=15)),
                ('last_club', models.CharField(max_length=15)),
                ('goal_of_first_club', models.IntegerField(blank=True, null=True)),
                ('goal_of_last_club', models.IntegerField(blank=True, null=True)),
                ('playing_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messagetoclubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('club', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dead_line', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='messageToRefree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('refree', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dead_line', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MesssageFromClubToPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('player', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dead_line', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Public_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_club', models.CharField(max_length=15)),
                ('last_club', models.CharField(max_length=15)),
                ('stadium_name', models.CharField(max_length=15)),
                ('playing_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='verificationcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_giver', models.CharField(blank=True, max_length=10, null=True)),
                ('player_code', models.CharField(max_length=10)),
                ('club_code', models.CharField(max_length=10)),
                ('refree_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter_name', models.CharField(max_length=15)),
                ('club_name', models.CharField(max_length=200, null=True)),
                ('propic', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=15)),
                ('propic', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('entry_birr', models.DecimalField(decimal_places=3, max_digits=5)),
                ('max_capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethiopia.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Refree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refree_name', models.CharField(max_length=15)),
                ('propic', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('birth_place', models.CharField(max_length=15)),
                ('birth_date', models.DateTimeField()),
                ('salary', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, null=True)),
                ('Player_name', models.CharField(max_length=15)),
                ('propic', models.ImageField(default='profile1.png', null=True, upload_to='')),
                ('birth_date', models.DateTimeField()),
                ('birth_place', models.CharField(max_length=15)),
                ('height', models.DecimalField(decimal_places=3, max_digits=5)),
                ('weight_in_newton', models.DecimalField(decimal_places=3, max_digits=5)),
                ('goal_scored', models.IntegerField(default=0)),
                ('yellow_card_seen', models.IntegerField(default=0)),
                ('red_card_seen', models.IntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('malia_number', models.IntegerField(default=-1)),
                ('position', models.CharField(max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
